{{- if .Values.ingress.enabled -}}
{{- $fullName := include "simple-page.fullname" . -}}
{{- $fullName := (print $fullName "-" .Values.build.number) -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ $fullName }}"
  namespace:  {{ .Values.namespace }}
  labels:
    app: {{ template "simple-page.name" . }}
    chart: {{ template "simple-page.chart" . }}
    release: "{{ .Release.Name }}-{{ .Values.build.number }}"
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - '{{ . }}'
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: "{{ $fullName }}"
              servicePort: http
  {{- end }}
{{- end }}

