apiVersion: v1
kind: Service
metadata:
  name: "{{ template "simple-page.fullname" . }}-{{ .Values.build.number }}"
  namespace:  {{ .Values.namespace }}
  labels:
    app: {{ template "simple-page.name" . }}
    chart: {{ template "simple-page.chart" . }}
    release: "{{ .Release.Name }}-{{ .Values.build.number }}"
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "simple-page.name" . }}
    release: "{{ .Release.Name }}-{{ .Values.build.number }}"